version: '3.8'

services:
  db:
    image: postgres:16
    container_name: zoo_db
    environment:
      POSTGRES_DB: zoo_lab3_db
      POSTGRES_USER: zoo_admin
      POSTGRES_PASSWORD: zoo123.
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - zoo_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zoo_admin -d zoo_lab3_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: zoo_api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://zoo_admin:zoo_password@db:5432/zoo_lab3_db"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: zoo_ui
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      API_URL: "http://backend:8000"
    volumes:
      - ./frontend:/app

volumes:
  zoo_data: